version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  web:
    image: plebotomist/reserve:v0.0.1
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 1m
    ports:
      # Replace <port> with the port that your app's web server
      # is listening inside the Docker container. If you need to
      # expose more ports, add them below.
      - 5013:5013
    volumes:
      # Uncomment to mount your data directories inside
      # the Docker container for storing persistent data
      # - ${APP_DATA_DIR}/foo:/foo
      # - ${APP_DATA_DIR}/bar:/bar

      # Uncomment to mount LND's data directory as read-only
      # inside the Docker container at path /lnd
      # - ${LND_DATA_DIR}:/lnd:ro

      # Uncomment to mount Bitcoin Core's data directory as
      # read-only inside the Docker container at path /bitcoin
      # - ${BITCOIN_DATA_DIR}:/bitcoin:ro
    environment:
      # Pass any environment variables to your app for configuration in the form:
      # VARIABLE_NAME: value
      #
      # Here are all the Umbrel provided variables that you can pass through to
      # your app to connect to Bitcoin Core, LND, Electrum and Tor:
      #
      # Bitcoin Core environment variables
      # $BITCOIN_NETWORK - Can be "mainnet", "testnet" or "regtest"
      # $BITCOIN_IP - Local IP of Bitcoin Core
      # $BITCOIN_P2P_PORT - P2P port
      # $BITCOIN_RPC_PORT - RPC port
      # $BITCOIN_RPC_USER - RPC username
      # $BITCOIN_RPC_PASS - RPC password
      # $BITCOIN_RPC_AUTH - RPC auth string
      #
      # LND environment variables
      # $LND_IP - Local IP of LND
      # $LND_GRPC_PORT - gRPC Port of LND
      # $LND_REST_PORT - REST Port of LND
      #
      # Electrum server environment variables
      # $ELECTRUM_IP - Local IP of Electrum server
      # $ELECTRUM_PORT - Port of Electrum server
      #
      # Tor proxy environment variables
      # $TOR_PROXY_IP - Local IP of Tor proxy
      # $TOR_PROXY_PORT - Port of Tor proxy
      #
      # App specific environment variables
      # $APP_HIDDEN_SERVICE - The address of the Tor hidden service your app will be exposed at
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 1
      RAILS_LOG_TO_STDOUT: 1
      RESERVE_POSTGRES: "User ID=postgres;Host=postgres;Port=5432;Database=reserve$BITCOIN_NETWORK"
  # If your app has more services, like a database container, you can define those
  # services below:
  # db:
  #   image: <docker-image>:<tag>
  #   ...
  postgres:
    image: postgres:9.6.20@sha256:82c335ccb6b60941cb860cbb8252c12f63fd3e27a0d15bce5bc6de110c02a2b4
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
        - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: $APP_BTCPAY_SERVER_DB_IP
